### ISSUE TITLE
[help me]: Modify dockerfile to connect between frontend(vue.js) and backend(express.js)

### ISSUE THREAD

**Issue by F9Uf** [F9Uf/Inventory-web-project#12]
Now, I've dockerfile in each folder: client, server and db directory. I use dockerfile to build the new images for part of them. And i use docker-compose to run them.

- **Client**, i've build nginx image to run vue.js application. 
- **DB**, i've build mysql:5.7 image for my database. 
- **Server**, i've build node image for my express backend.

Although, I can connect between Server and DB image. So, I would like to connect Client and Server but i can't. **Please help me to edit/modify/new docker-compose or dockerfile for it workd : )**

### Thank you

**Comment by F9Uf** [comment]
Update: I've set proxy in [vue.config.js](https://github.com/F9Uf/Inventory-web-project/blob/master/client/vue.config.js) but i run (docker-compose up), _**nginx is error 405.**_ 😢

**Comment by robrotheram** [comment]
Happy hacktoberfest the PR #14 fixes the issue you were having. Your backbend sever listens on port 5000 so you need to get nginx to proxy all api requests to server.
