### ISSUE TITLE
employee.controller.js:31: add permisstion

### ISSUE THREAD

**Issue by 0pdd** [F9Uf/Inventory-web-project#5]
The puzzle `5-c8896135` from #5 has to be resolved: 

https://github.com/F9Uf/Inventory-web-project/blob/170c5b0feff8d859095bf24095d10f9f426af2e3/server/v1/controllers/employee.controller.js#L31-L31

The puzzle was created by F9Uf on 28-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#5](https://github.com/F9Uf/Inventory-web-project/issues/5) is still not solved.

**Comment by F9Uf** [comment]
### More Detail
 [ ] employee can update only their own information
- [ ] manager can update all employees
- [ ] shop manager can update only shop's own information (not sure)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#unknown]() is solved here.
